function [layers, options] = NetParams_LSTM(numHiddenUnits, maxEpochs)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

inputSize = 1;
%numHiddenUnits = 14;
numClasses = 2;

layers = [ ...
    sequenceInputLayer(inputSize, 'Name', 'input')
    lstmLayer(numHiddenUnits,'OutputMode','sequence', 'Name', 'LSTM')
    fullyConnectedLayer(numHiddenUnits)
    fullyConnectedLayer(floor(numHiddenUnits/2))
    fullyConnectedLayer(numClasses, 'Name', 'output')
    regressionLayer('Name', 'regression')];

%maxEpochs = 500;
miniBatchSize = 1;

options = trainingOptions('adam', ...
    'ExecutionEnvironment','gpu', ...
    'GradientThreshold',1, ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'SequenceLength','longest', ...
    'Shuffle','never', ...
    'Verbose',0);%, ...
    %'CheckpointPath', pwd);%, ...
    %'Plots','training-progress');
end

