function [layers, options] = NetParams_LSTM(numHiddenUnits, maxEpochs)

inputSize = 1;
numClasses = 1;

layers = [ ...
    sequenceInputLayer(inputSize, 'Name', 'input')
    lstmLayer(numHiddenUnits,'OutputMode','sequence', 'Name', 'LSTM')
    fullyConnectedLayer(numClasses, 'Name', 'output')
    regressionLayer('Name', 'regression')];

miniBatchSize = 1;

options = trainingOptions('adam', ...
    'ExecutionEnvironment','cpu', ...
    'GradientThreshold',1, ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'SequenceLength','longest', ...
    'Shuffle','never', ...
    'Verbose',0);
end

