function [layers, options] = NetParams_LSTM(lstmNeurons, layer1Neurons, maxEpochs)

inputSize = 1;
numClasses = 2;

layers = [ ...
    sequenceInputLayer(inputSize, 'Name', 'input')
    lstmLayer(lstmNeurons,'OutputMode','sequence', 'Name', 'LSTM')
    fullyConnectedLayer(layer1Neurons, 'Name', 'mid')
    fullyConnectedLayer(numClasses, 'Name', 'output')
    regressionLayer('Name', 'regression')];

miniBatchSize = 1;

options = trainingOptions('adam', ...
    'ExecutionEnvironment','gpu', ...
    'GradientThreshold',1, ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'SequenceLength','longest', ...
    'Shuffle','never', ...
    'Verbose',0);
end

